### ISSUE TITLE
Support selecting (and copying as a biproduct) response meta data

### ISSUE THREAD

**Issue by jwtly10** [chapar-rest/chapar#30]
**Is your feature request related to a problem? Please describe.**
Great work with Chapar so far, I have been looking for a lightweight postman alternative for a while, and once you support scripting (I may be able to help with this) that'll probably be enough for me to make the switch for the majority of my workloads.

I have never used the GioUI framework so I haven't looked at fixing this myself, but can we support text selection events on response headers/cookies? 

The 'copy' button copies the body response which is nice, but there are times where I need to copy response headers and response cookies. I think the easiest way would just be supporting the text selection event for this ValuesTable, perhaps just switching out the Label widget would work?

This is the data I am referring too:
<img width="442" alt="image" src="https://github.com/chapar-rest/chapar/assets/39057715/6f117aa1-651f-47fd-9e2a-022e22ffb877">

Again.. great work! Thanks

**Comment by mirzakhany** [comment]
Thanks for reporting this @jwtly10 I'll fix it soon. 👍
