### ISSUE TITLE
Beta's `install-linux.sh` doesn't "just work" (expects a dir that's missing, needs sudo without prior notice)

### ISSUE THREAD

**Issue by metaleap** [chapar-rest/chapar#48]
Both for the functionality of the app itself and to see GIO UI in action, I downloaded the latest Release ("first beta") and extracted it. Then I did this in the terminal:

```
[~/a/Chapar_linux_amd64] ./install-linux.sh 
install: cannot stat '/home/_/a/Chapar_linux_amd64/chapar': No such file or directory
mkdir: cannot create directory ‘/usr/local/share/applications’: Permission denied
```

Well I can probably still get things going from these admittedly seemingly trivial 2 complaints — **but** maybe you want to pre-empt this UX so here's an Issue for that  =)  after all, an app as this could become really quite popular given the Electron bloat of the Postman / Insomnia etc. space!

**Comment by metaleap** [comment]
Well, after I manually did `mkdir chapar` the shell script now says `install: omitting directory '/home/_/a/Chapar_linux_amd64/chapar'` ... so I guess the `chapar` dir should have been in the `.tar.gz` but wasn't?

**Comment by mirzakhany** [comment]
Thanks for reporting this. I removed the Linux version from release for now until I can fix this. 🙏
