### ISSUE TITLE
URL scheme and file scheme support so a file extension of .chap opens the gui ?

### ISSUE THREAD

**Issue by gedw99** [chapar-rest/chapar#52]
The problem is that it can be hard to maintain a context .

also it’s a bonus because people can share their .chap project smdescriotions and the chapter software will be opened / installed off the App Store.

The wY this works with gio is to support url scheme and their is a repo that does it.

https://github.com/inkeliz/deeplink-demo

works for desktop and mobile and web .

on desktop it will open the .chap file extension and open the chapter app, of take you to the App Store or web site.

On mobile it will do the same as desktop

on web it will check if you have a cheaper app installed and if so open it , otherwise directing you to the web site .

the version of the gio cmd is specific though and I think it’s going into mainline gio cmd but taking a while.

for now though it’s just a mater if using his fork.

I wish I had more time to work on this but I don’t so I just wanted to quickly get this in as a future feature. it’s kind of magical when you get it working :)

**Comment by mirzakhany** [comment]
Hi @gedw99 
All configuration of app is stored as yaml files in file system. it varies in different OS, for example its located at `/home/.config/chapar` in linux. the point of having configurations as files is that user can decide how to share, copy or edit them. 

So one can make a private repository and push configs to that and let others also pull them. or use other sync tools of their choice.
