### ISSUE TITLE
Can't create Restful Requst under collection

### ISSUE THREAD

**Issue by Monirzadeh** [chapar-rest/chapar#55]
**Describe the bug**
If you create a collection you see a 3 dot beside the collection name you can't `Add HTTP Request` 
if you press that create GRPC request instead

**To Reproduce**
1. Go to new
2. Click on Collection
3. press 3 dot beside `New Collection`
4. Click on `Add HTTP Request` 
5. As you see GRPC request created instead of Restful request under collection

**Expected behavior**
Create Restful Request inside collection collection 

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.2.1-beta

**Comment by mirzakhany** [comment]
hi @Monirzadeh Thanks for reporting this. I'll fix its soon.
