### ISSUE TITLE
Duplicate collection

### ISSUE THREAD

**Issue by Monirzadeh** [chapar-rest/chapar#60]
**Is your feature request related to a problem? Please describe.**
sometimes you have lots of collection with too many request (for example work with different version of program)

currently you can Duplicate single request but it useful if  add Duplicate for collection too.
so we can faster duplicate collection (set of Request) and update them later for specific version of program or use case

**Describe the solution you'd like**
add `Duplicate` to 3 dot of collection that generate a duplicate collection with all request inside original Collection

**Comment by mirzakhany** [comment]
Sound reasonable 👍 I'll put in my todo list. 

Just a suggestion to solve your problem for now, you can copy items and collections in file system. if you are on linux, go to `~/.config/chapar` and there you can find workspaces and requests inside it. make a copy of the collection collection directory you want to duplicate and open `_collection.yaml` file inside the directory and change the uuid and name of it to something new and restart the app.
