### ISSUE TITLE
Chapar crach when switch between enviroment tabs

### ISSUE THREAD

**Issue by Monirzadeh** [chapar-rest/chapar#63]
**Describe the bug**
when you have multiple workspace Envs tab switching will crash chapar 

**To Reproduce**
1. Go to `Workspace` and create new `Worksapce` name `workspace1`
2. Now you should have 2 workspace `Default Workspace` and `workspace1`
3. Go to `Envs`
4. Select `Default Workspace` from top of the page and than press `+ New` to create a new environment (name will be `New Environment`)
5. Done same things for `workspace1`
6. Click on `New Environment` that you create  inside `workspace1` a tab will open
7. Switch workspace to `Default Workspace` and open `New Environment` inside `Default Workspace` that a new tab will open
8. Now you have two tab open both name is `New Environment`
9. Click on other open tab
10. as you see chaparral will crash

**Expected behavior**
Program not crash if you switch between Envs from different workspace

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.2.3

**Comment by mirzakhany** [comment]
Hi @Monirzadeh Im aware of this issue. at this stage Chapar is not able to work cross workspaces.
