### ISSUE TITLE
improve response section

### ISSUE THREAD

**Issue by Monirzadeh** [chapar-rest/chapar#69]
**Is your feature request related to a problem? Please describe.**
currently chapar simply show json response but it can improve. two improvement can make it better
1. add syntax highlight for json response
2. currently for copy you can click copy button (copy all the response) or select text with mouse but when you try to select part of response you cant select more than one line. please make it possible to select more that one line

**Comment by mirzakhany** [comment]
Hi, @Monirzadeh 
This is a known issue and one of the things I have planned to solve. 
Json viewer is in fact a list that render each line using a label widget, reason being the limitation of text widget when rendering large texts with can cause app to crash. 

current solution has it own limitation but at least can show the result. 
Possible fix is to build a widget that supports only rendering the visible part of the text.

**Comment by mirzakhany** [comment]
It's addressed in #100 and will be available in next release.
