### ISSUE TITLE
Release not update version in desktop entry

### ISSUE THREAD

**Issue by Monirzadeh** [chapar-rest/chapar#77]
**Describe the bug**
Desktop entry file in release version not update for each release and allways be 0.1.0
**To Reproduce**
1. Download any release of chapar
2. extract that
3. open file `desktop-assets/chapar.desktop`
4. See `Version=0.1.0` regaurdless of real version

**Expected behavior**
in each release update the version in release file

**Additional context**
i do some test to add chapar to aur and it is one of that should consider
not bad if add hash of files in each release.

**Comment by mirzakhany** [comment]
Hi @Monirzadeh thanks for this issue and PR. 
I'll fix the binary build as well to include app version in the code with ldflags. 

Regarding Aur, it would be nice to do. if you could do it, it's much appreciated. 👍

**Comment by mirzakhany** [comment]
Sounds like a good idea. 

> i don't see anywhere in ui show the version of current running chapar. not bad to add that to welcome page or anywhere else (or at least flag --version)

I will soon add it to bottom of sidebar or somewhere in header.
